import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import Profile from "../public/profile.png";
import Design from "../public/design.png";
import Code from "../public/code.png";
import Consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Indra Saputra Idrus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          {/* Nav */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-slate-200">Ndrainz</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl dark:text-slate-200" onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {/* end Nav */}

          {/* Hero */}
          <div className="text-center p-10">
            <h2 className="text-5xl text-teal-600 font-medium md:text-6xl">
              Indra Saputra Idrus
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-slate-200">
              Student and Programmer
            </h3>
            <p className="text-md py-5 leading-5 text-gray-800 md:text-lg max-w-xl mx-auto dark:text-gray-300">
              Belajar programming dan web development
            </p>
          </div>

          <div className="text-4xl flex justify-center gap-10 py-3 text-gray-600 dark:text-gray-300">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={Profile} layout="fill" objectFit="cover" />
          </div>
          {/* end Hero */}
        </section>

        <section className="mt-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-slate-200">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Lorem ipsum dolor sit amet{" "}
              <span className="text-teal-500">consectetur</span> adipisicing
              elit. <span className="text-teal-500">Repudiandae</span> eligendi
              tenetur nostrum qui iste voluptates?
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut
              nesciunt et delectus eius.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-200">
              <Image src={Design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="py-2">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Necessitatibus, excepturi.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-200">
              <Image src={Code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="py-2">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Necessitatibus, excepturi.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-200">
              <Image src={Consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="py-2">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Necessitatibus, excepturi.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-slate-200">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Lorem ipsum dolor sit amet{" "}
              <span className="text-teal-500">consectetur</span> adipisicing
              elit. <span className="text-teal-500">Repudiandae</span> eligendi
              tenetur nostrum qui iste voluptates?
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut
              nesciunt et delectus eius.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
